
.phony: build deadcode test

build:
	go build -o yttranscript ./cmd/yttranscript/...

test:
	go test -v ./...

deadcode:
	@#go tool golang.org/x/tools/cmd/deadcode -f='{{println .Path}}{{range .Funcs}}{{printf "\t%s\n" .Name}}{{end}}{{println}}' -test ./...
	go tool golang.org/x/tools/cmd/deadcode ./...
